### PR TITLE
Dand 43 scripts for automation

### PR DESCRIPTION
**Pull request by OllaAshour**
**What does this PR do?**
-Add script to install any missing/required tools and dependencies
-Add gem files to maintain same environment for all developers
-Clean project
-Run pod install/update
-Test project 
-Run OCLint checks
-Add clang-format to format objective c code.

**Associated JIRA Tickets:**
https://segmentcontractors.atlassian.net/browse/DAND-47=3

### CODE REVIEW

**Review by brennan — CHANGES_REQUESTED** [review]
hey @OllaAshour, it looks as if this PR combines work on automation scripts as well as changes to the Facebook integration. Would you be able to split this work into two separate PRs? Thanks!

**Comment by OllaAshour** [comment]
@brennan Hey Brennan. It doesn't. Facebook integration was the initial destination added which has already been merged to master. But because somehow git history is not showing that the DAND-16 has been merged into master, it's including the commits of DAND-16 as I branched from it.
I tried to fix it but couldn't find a way. I was having a discussion with brie about it this morning.
Only thing I haven't done is to do like I did with Firebase integration, to create a new branch and cherry pick the commits.

**Review by brennan — CHANGES_REQUESTED** [review]
Hey @OllaAshour, I experienced a few issues with each of these scripts. See below - thanks!

**./lint.sh**
 Formatting Code
 Running OClint
note: Using new build system

** CLEAN SUCCEEDED **

- I'm not sure what the below error is. If this is expected - or if there's a workaround - would you be able to add it to a Readme?

❌  error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YKC2MJQDVL" with a private key was found. (in target 'Segment-Facebook' from project 'Segment-Facebook')


** BUILD FAILED **

Skipping /Users/brennan.gamwell/dev/src/github.com/segmentio/analytics-ios-integrations/—e. Compile command not found.
Skipping /Users/brennan.gamwell/dev/src/github.com/segmentio/analytics-ios-integrations/Segment_Facebook.h. Compile command not found.
Skipping /Users/brennan.gamwell/dev/src/github.com/segmentio/analytics-ios-integrations/Segment_Facebook_vers.c. Compile command not found.
Skipping /Users/brennan.gamwell/dev/src/github.com/segmentio/analytics-ios-integrations/build. Compile command not found.
 Linting pod spec

 -> Segment-Facebook-App-Events (1.0.4)
    - WARN  | source: Git sources should specify a tag.
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'Analytics' from project 'Pods')

[!] Segment-Facebook-App-Events did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.


**./test.sh**
-bash: ./test.sh: Permission denied

- So I ran `chmod u+x test.sh`
- Would you be able to update permissions for all scripts so they can be run out of the box?

**./test.sh**
xcodebuild: error: The directory /Users/brennan.gamwell/dev/src/github.com/segmentio/analytics-ios-integrations/Scripts does not contain an Xcode project, workspace or package.

- It looks like the previous script was meant to be run from the home directory of the repo, but this one isn't. Would you be able to ensure the scripts are consistent in that they can all be run from the same directory. I think it may be a good idea to make it possible to run from either the repo's home directory, or from within the `Scripts` directory itself.

./Scripts/test.sh
note: Using new build system
note: Planning build
note: Constructing build description
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YKC2MJQDVL" with a private key was found. (in target 'Segment-FacebookTests' from project 'Segment-Facebook')
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YKC2MJQDVL" with a private key was found. (in target 'Segment-Facebook' from project 'Segment-Facebook')

Test session results, code coverage, and logs:
	/Users/brennan.gamwell/Library/Developer/Xcode/DerivedData/iOS-Integrations-grjbplxhxhfjmuhegrxqvthgmhkj/Logs/Test/Test-Segment-Facebook-2020.01.13_13-47-42--0800.xcresult

 - Would you be able to document the below issue in a Readme, if you're familiar with the issue?

Testing failed:
	No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YKC2MJQDVL" with a private key was found.
	Testing cancelled because the build failed.

** TEST FAILED **


**Scripts/update.sh**
-bash: Scripts/update.sh: Permission denied

- So I ran `chmod u+x update.sh`
- Same here, can you update the permission so a user can run out of the box?
- Also, can you ensure a user can run this script from the repo's main directory, or the `Scripts` directory?
- Also, would you be able to add instructions on installing the correct version of Ruby to the Readme?

Scripts/update.sh
Installing and Updating Integrations dependencies
Scripts/update.sh: /usr/local/bin/bundle: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory
Installing and Updating Example dependencies
Scripts/update.sh: /usr/local/bin/bundle: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by briemcnally** [comment]
@OllaAshour can you resolve the merge conflicts on this PR as well?

**Comment by OllaAshour** [comment]
Closing this PR and opening a new PR to reflect correct commit history.

**Comment by briemcnally** [comment]
Hey @OllaAshour  a few other comments from me from testing these scripts: 

1. `./lint.sh` is erroring with `./lint.sh: /usr/local/bin/xcpretty: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory`. Do you know how to resolve this? 
I also see this error `./lint.sh: line 23: oclint-json-compilation-database: command not found`
This is the full output in my terminal from that command: 
Screen Shot 2020-01-13 at 4 38 44 PM
2. `./test.sh` does not work from within the Script directory. From root directory when I run `Scipts/test.sh` I get the same error @brennan mentioned above. Again here is a screenshot:
Screen Shot 2020-01-13 at 4 57 03 PM

In general can we improve documentation on running scripts and where they need to be run from. Some are in Scripts directory. Some root directory from what I can tell.

Also would you mind providing more information about how to resolve the two issues stated above in the Realeasing.md or Read.me if you are familiar with them since @brennan and I both are getting the same errors?

I got the `./update.sh` to work after I `bundle install` but we might want to document that somewhere. 

I think in the Readme we should state define the these steps and any FAQs about errors : 
1. `update` <- this should definitely be run first before testing 
2. `check ` <- This added OClint which I didn't have installed
3. `lint`
4. `test`

Then in the releasing we can just say run lint and test.

**Pull request closed without merging**
